// Generated by gencpp from file atlas_msgs/AtlasFilters.msg
// DO NOT EDIT!


#ifndef ATLAS_MSGS_MESSAGE_ATLASFILTERS_H
#define ATLAS_MSGS_MESSAGE_ATLASFILTERS_H

#include <ros/service_traits.h>


#include <atlas_msgs/AtlasFiltersRequest.h>
#include <atlas_msgs/AtlasFiltersResponse.h>


namespace atlas_msgs
{

struct AtlasFilters
{

typedef AtlasFiltersRequest Request;
typedef AtlasFiltersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AtlasFilters
} // namespace atlas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atlas_msgs::AtlasFilters > {
  static const char* value()
  {
    return "c10edfabe7696f91f51fb8486565f5ac";
  }

  static const char* value(const ::atlas_msgs::AtlasFilters&) { return value(); }
};

template<>
struct DataType< ::atlas_msgs::AtlasFilters > {
  static const char* value()
  {
    return "atlas_msgs/AtlasFilters";
  }

  static const char* value(const ::atlas_msgs::AtlasFilters&) { return value(); }
};


// service_traits::MD5Sum< ::atlas_msgs::AtlasFiltersRequest> should match 
// service_traits::MD5Sum< ::atlas_msgs::AtlasFilters > 
template<>
struct MD5Sum< ::atlas_msgs::AtlasFiltersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::AtlasFilters >::value();
  }
  static const char* value(const ::atlas_msgs::AtlasFiltersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::AtlasFiltersRequest> should match 
// service_traits::DataType< ::atlas_msgs::AtlasFilters > 
template<>
struct DataType< ::atlas_msgs::AtlasFiltersRequest>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::AtlasFilters >::value();
  }
  static const char* value(const ::atlas_msgs::AtlasFiltersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atlas_msgs::AtlasFiltersResponse> should match 
// service_traits::MD5Sum< ::atlas_msgs::AtlasFilters > 
template<>
struct MD5Sum< ::atlas_msgs::AtlasFiltersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::AtlasFilters >::value();
  }
  static const char* value(const ::atlas_msgs::AtlasFiltersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::AtlasFiltersResponse> should match 
// service_traits::DataType< ::atlas_msgs::AtlasFilters > 
template<>
struct DataType< ::atlas_msgs::AtlasFiltersResponse>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::AtlasFilters >::value();
  }
  static const char* value(const ::atlas_msgs::AtlasFiltersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATLAS_MSGS_MESSAGE_ATLASFILTERS_H
