// Generated by gencpp from file atlas_msgs/GetJointDamping.msg
// DO NOT EDIT!


#ifndef ATLAS_MSGS_MESSAGE_GETJOINTDAMPING_H
#define ATLAS_MSGS_MESSAGE_GETJOINTDAMPING_H

#include <ros/service_traits.h>


#include <atlas_msgs/GetJointDampingRequest.h>
#include <atlas_msgs/GetJointDampingResponse.h>


namespace atlas_msgs
{

struct GetJointDamping
{

typedef GetJointDampingRequest Request;
typedef GetJointDampingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointDamping
} // namespace atlas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atlas_msgs::GetJointDamping > {
  static const char* value()
  {
    return "ac3412a634e22520e6b32a1a83777a10";
  }

  static const char* value(const ::atlas_msgs::GetJointDamping&) { return value(); }
};

template<>
struct DataType< ::atlas_msgs::GetJointDamping > {
  static const char* value()
  {
    return "atlas_msgs/GetJointDamping";
  }

  static const char* value(const ::atlas_msgs::GetJointDamping&) { return value(); }
};


// service_traits::MD5Sum< ::atlas_msgs::GetJointDampingRequest> should match 
// service_traits::MD5Sum< ::atlas_msgs::GetJointDamping > 
template<>
struct MD5Sum< ::atlas_msgs::GetJointDampingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::GetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::GetJointDampingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::GetJointDampingRequest> should match 
// service_traits::DataType< ::atlas_msgs::GetJointDamping > 
template<>
struct DataType< ::atlas_msgs::GetJointDampingRequest>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::GetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::GetJointDampingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atlas_msgs::GetJointDampingResponse> should match 
// service_traits::MD5Sum< ::atlas_msgs::GetJointDamping > 
template<>
struct MD5Sum< ::atlas_msgs::GetJointDampingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::GetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::GetJointDampingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::GetJointDampingResponse> should match 
// service_traits::DataType< ::atlas_msgs::GetJointDamping > 
template<>
struct DataType< ::atlas_msgs::GetJointDampingResponse>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::GetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::GetJointDampingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATLAS_MSGS_MESSAGE_GETJOINTDAMPING_H
