// Generated by gencpp from file atlas_msgs/ResetControls.msg
// DO NOT EDIT!


#ifndef ATLAS_MSGS_MESSAGE_RESETCONTROLS_H
#define ATLAS_MSGS_MESSAGE_RESETCONTROLS_H

#include <ros/service_traits.h>


#include <atlas_msgs/ResetControlsRequest.h>
#include <atlas_msgs/ResetControlsResponse.h>


namespace atlas_msgs
{

struct ResetControls
{

typedef ResetControlsRequest Request;
typedef ResetControlsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetControls
} // namespace atlas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atlas_msgs::ResetControls > {
  static const char* value()
  {
    return "132418be2559866cd92987f80ed5ce8a";
  }

  static const char* value(const ::atlas_msgs::ResetControls&) { return value(); }
};

template<>
struct DataType< ::atlas_msgs::ResetControls > {
  static const char* value()
  {
    return "atlas_msgs/ResetControls";
  }

  static const char* value(const ::atlas_msgs::ResetControls&) { return value(); }
};


// service_traits::MD5Sum< ::atlas_msgs::ResetControlsRequest> should match 
// service_traits::MD5Sum< ::atlas_msgs::ResetControls > 
template<>
struct MD5Sum< ::atlas_msgs::ResetControlsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::ResetControls >::value();
  }
  static const char* value(const ::atlas_msgs::ResetControlsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::ResetControlsRequest> should match 
// service_traits::DataType< ::atlas_msgs::ResetControls > 
template<>
struct DataType< ::atlas_msgs::ResetControlsRequest>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::ResetControls >::value();
  }
  static const char* value(const ::atlas_msgs::ResetControlsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atlas_msgs::ResetControlsResponse> should match 
// service_traits::MD5Sum< ::atlas_msgs::ResetControls > 
template<>
struct MD5Sum< ::atlas_msgs::ResetControlsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::ResetControls >::value();
  }
  static const char* value(const ::atlas_msgs::ResetControlsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::ResetControlsResponse> should match 
// service_traits::DataType< ::atlas_msgs::ResetControls > 
template<>
struct DataType< ::atlas_msgs::ResetControlsResponse>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::ResetControls >::value();
  }
  static const char* value(const ::atlas_msgs::ResetControlsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATLAS_MSGS_MESSAGE_RESETCONTROLS_H
