// Generated by gencpp from file atlas_msgs/SetJointDamping.msg
// DO NOT EDIT!


#ifndef ATLAS_MSGS_MESSAGE_SETJOINTDAMPING_H
#define ATLAS_MSGS_MESSAGE_SETJOINTDAMPING_H

#include <ros/service_traits.h>


#include <atlas_msgs/SetJointDampingRequest.h>
#include <atlas_msgs/SetJointDampingResponse.h>


namespace atlas_msgs
{

struct SetJointDamping
{

typedef SetJointDampingRequest Request;
typedef SetJointDampingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointDamping
} // namespace atlas_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::atlas_msgs::SetJointDamping > {
  static const char* value()
  {
    return "7a171b40177337e0eafdb8776fe3c1da";
  }

  static const char* value(const ::atlas_msgs::SetJointDamping&) { return value(); }
};

template<>
struct DataType< ::atlas_msgs::SetJointDamping > {
  static const char* value()
  {
    return "atlas_msgs/SetJointDamping";
  }

  static const char* value(const ::atlas_msgs::SetJointDamping&) { return value(); }
};


// service_traits::MD5Sum< ::atlas_msgs::SetJointDampingRequest> should match 
// service_traits::MD5Sum< ::atlas_msgs::SetJointDamping > 
template<>
struct MD5Sum< ::atlas_msgs::SetJointDampingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::SetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::SetJointDampingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::SetJointDampingRequest> should match 
// service_traits::DataType< ::atlas_msgs::SetJointDamping > 
template<>
struct DataType< ::atlas_msgs::SetJointDampingRequest>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::SetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::SetJointDampingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::atlas_msgs::SetJointDampingResponse> should match 
// service_traits::MD5Sum< ::atlas_msgs::SetJointDamping > 
template<>
struct MD5Sum< ::atlas_msgs::SetJointDampingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::atlas_msgs::SetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::SetJointDampingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::atlas_msgs::SetJointDampingResponse> should match 
// service_traits::DataType< ::atlas_msgs::SetJointDamping > 
template<>
struct DataType< ::atlas_msgs::SetJointDampingResponse>
{
  static const char* value()
  {
    return DataType< ::atlas_msgs::SetJointDamping >::value();
  }
  static const char* value(const ::atlas_msgs::SetJointDampingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ATLAS_MSGS_MESSAGE_SETJOINTDAMPING_H
