(cl:defpackage handle_msgs-msg
  (:use )
  (:export
   "<HANDLECONTROL>"
   "HANDLECONTROL"
   "<HANDLESENSORS>"
   "HANDLESENSORS"
   "<HANDLESENSORSCALIBRATED>"
   "HANDLESENSORSCALIBRATED"
   "<FINGER>"
   "FINGER"
   "<CABLETENSION>"
   "CABLETENSION"
   "<HANDLECOLLISIONS>"
   "HANDLECOLLISIONS"
   "<COLLISION>"
   "COLLISION"
  ))

