(cl:in-package atlas_msgs-srv)
(cl:export '(DAMPING_COEFFICIENTS-VAL
          DAMPING_COEFFICIENTS
          DAMPING_COEFFICIENTS_MIN-VAL
          DAMPING_COEFFICIENTS_MIN
          DAMPING_COEFFICIENTS_MAX-VAL
          DAMPING_COEFFICIENTS_MAX
          SUCCESS-VAL
          SUCCESS
          STATUS_MESSAGE-VAL
          STATUS_MESSAGE
))