(cl:defpackage atlas_msgs-srv
  (:use )
  (:export
   "RESETCONTROLS"
   "<RESETCONTROLS-REQUEST>"
   "RESETCONTROLS-REQUEST"
   "<RESETCONTROLS-RESPONSE>"
   "RESETCONTROLS-RESPONSE"
   "SETJOINTDAMPING"
   "<SETJOINTDAMPING-REQUEST>"
   "SETJOINTDAMPING-REQUEST"
   "<SETJOINTDAMPING-RESPONSE>"
   "SETJOINTDAMPING-RESPONSE"
   "ATLASFILTERS"
   "<ATLASFILTERS-REQUEST>"
   "ATLASFILTERS-REQUEST"
   "<ATLASFILTERS-RESPONSE>"
   "ATLASFILTERS-RESPONSE"
   "GETJOINTDAMPING"
   "<GETJOINTDAMPING-REQUEST>"
   "GETJOINTDAMPING-REQUEST"
   "<GETJOINTDAMPING-RESPONSE>"
   "GETJOINTDAMPING-RESPONSE"
  ))

