(cl:in-package atlas_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          EFFORT-VAL
          EFFORT
          KP_POSITION-VAL
          KP_POSITION
          KI_POSITION-VAL
          KI_POSITION
          KD_POSITION-VAL
          KD_POSITION
          KP_VELOCITY-VAL
          KP_VELOCITY
          I_EFFORT_MIN-VAL
          I_EFFORT_MIN
          I_EFFORT_MAX-VAL
          I_EFFORT_MAX
          K_EFFORT-VAL
          K_EFFORT
          ORIENTATION-VAL
          ORIENTATION
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          L_FOOT-VAL
          L_FOOT
          R_FOOT-VAL
          R_FOOT
          L_HAND-VAL
          L_HAND
          R_HAND-VAL
          R_HAND
))