// Generated by gencpp from file handle_msgs/Finger.msg
// DO NOT EDIT!


#ifndef HANDLE_MSGS_MESSAGE_FINGER_H
#define HANDLE_MSGS_MESSAGE_FINGER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace handle_msgs
{
template <class ContainerAllocator>
struct Finger_
{
  typedef Finger_<ContainerAllocator> Type;

  Finger_()
    : proximal()
    , distal()  {
    }
  Finger_(const ContainerAllocator& _alloc)
    : proximal(_alloc)
    , distal(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _proximal_type;
  _proximal_type proximal;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _distal_type;
  _distal_type distal;




  typedef boost::shared_ptr< ::handle_msgs::Finger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handle_msgs::Finger_<ContainerAllocator> const> ConstPtr;

}; // struct Finger_

typedef ::handle_msgs::Finger_<std::allocator<void> > Finger;

typedef boost::shared_ptr< ::handle_msgs::Finger > FingerPtr;
typedef boost::shared_ptr< ::handle_msgs::Finger const> FingerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handle_msgs::Finger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handle_msgs::Finger_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace handle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'handle_msgs': ['/home/chalmers/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/drcsim/handle_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::handle_msgs::Finger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handle_msgs::Finger_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handle_msgs::Finger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handle_msgs::Finger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handle_msgs::Finger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handle_msgs::Finger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handle_msgs::Finger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "143bc4ae61f1c2415fee6b36cd2011b8";
  }

  static const char* value(const ::handle_msgs::Finger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x143bc4ae61f1c241ULL;
  static const uint64_t static_value2 = 0x5fee6b36cd2011b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::handle_msgs::Finger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handle_msgs/Finger";
  }

  static const char* value(const ::handle_msgs::Finger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handle_msgs::Finger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This finger definition is used for different sensors in the HandleSensors \n\
# message type.  \n\
\n\
float32[] proximal\n\
float32[] distal\n\
\n\
";
  }

  static const char* value(const ::handle_msgs::Finger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handle_msgs::Finger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.proximal);
      stream.next(m.distal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Finger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handle_msgs::Finger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handle_msgs::Finger_<ContainerAllocator>& v)
  {
    s << indent << "proximal[]" << std::endl;
    for (size_t i = 0; i < v.proximal.size(); ++i)
    {
      s << indent << "  proximal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.proximal[i]);
    }
    s << indent << "distal[]" << std::endl;
    for (size_t i = 0; i < v.distal.size(); ++i)
    {
      s << indent << "  distal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDLE_MSGS_MESSAGE_FINGER_H
