# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from atlas_msgs/SynchronizationStatistics.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SynchronizationStatistics(genpy.Message):
  _md5sum = "27bc1701ef8ff889822573f985ebb2b6"
  _type = "atlas_msgs/SynchronizationStatistics"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 delay_in_step         # instantaneous delay per simulation step, this must be less than delayMaxPerStep.
float64 delay_in_window       # total delay in current window period.
float64 delay_window_remain   # time left in current window period, before next budget reset.
"""
  __slots__ = ['delay_in_step','delay_in_window','delay_window_remain']
  _slot_types = ['float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       delay_in_step,delay_in_window,delay_window_remain

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SynchronizationStatistics, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.delay_in_step is None:
        self.delay_in_step = 0.
      if self.delay_in_window is None:
        self.delay_in_window = 0.
      if self.delay_window_remain is None:
        self.delay_window_remain = 0.
    else:
      self.delay_in_step = 0.
      self.delay_in_window = 0.
      self.delay_window_remain = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.delay_in_step, _x.delay_in_window, _x.delay_window_remain))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.delay_in_step, _x.delay_in_window, _x.delay_window_remain,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.delay_in_step, _x.delay_in_window, _x.delay_window_remain))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.delay_in_step, _x.delay_in_window, _x.delay_window_remain,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d = struct.Struct("<3d")
