// Generated by gencpp from file sandia_hand_msgs/SetJointLimitPolicy.msg
// DO NOT EDIT!


#ifndef SANDIA_HAND_MSGS_MESSAGE_SETJOINTLIMITPOLICY_H
#define SANDIA_HAND_MSGS_MESSAGE_SETJOINTLIMITPOLICY_H

#include <ros/service_traits.h>


#include <sandia_hand_msgs/SetJointLimitPolicyRequest.h>
#include <sandia_hand_msgs/SetJointLimitPolicyResponse.h>


namespace sandia_hand_msgs
{

struct SetJointLimitPolicy
{

typedef SetJointLimitPolicyRequest Request;
typedef SetJointLimitPolicyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointLimitPolicy
} // namespace sandia_hand_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicy > {
  static const char* value()
  {
    return "e910d3ed1e2e8ad67a9ceacdc38b1c45";
  }

  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicy&) { return value(); }
};

template<>
struct DataType< ::sandia_hand_msgs::SetJointLimitPolicy > {
  static const char* value()
  {
    return "sandia_hand_msgs/SetJointLimitPolicy";
  }

  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicy&) { return value(); }
};


// service_traits::MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicyRequest> should match 
// service_traits::MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicy > 
template<>
struct MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicy >::value();
  }
  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sandia_hand_msgs::SetJointLimitPolicyRequest> should match 
// service_traits::DataType< ::sandia_hand_msgs::SetJointLimitPolicy > 
template<>
struct DataType< ::sandia_hand_msgs::SetJointLimitPolicyRequest>
{
  static const char* value()
  {
    return DataType< ::sandia_hand_msgs::SetJointLimitPolicy >::value();
  }
  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicyResponse> should match 
// service_traits::MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicy > 
template<>
struct MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicy >::value();
  }
  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sandia_hand_msgs::SetJointLimitPolicyResponse> should match 
// service_traits::DataType< ::sandia_hand_msgs::SetJointLimitPolicy > 
template<>
struct DataType< ::sandia_hand_msgs::SetJointLimitPolicyResponse>
{
  static const char* value()
  {
    return DataType< ::sandia_hand_msgs::SetJointLimitPolicy >::value();
  }
  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SANDIA_HAND_MSGS_MESSAGE_SETJOINTLIMITPOLICY_H
