// Generated by gencpp from file sandia_hand_msgs/SetJointLimitPolicyResponse.msg
// DO NOT EDIT!


#ifndef SANDIA_HAND_MSGS_MESSAGE_SETJOINTLIMITPOLICYRESPONSE_H
#define SANDIA_HAND_MSGS_MESSAGE_SETJOINTLIMITPOLICYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sandia_hand_msgs
{
template <class ContainerAllocator>
struct SetJointLimitPolicyResponse_
{
  typedef SetJointLimitPolicyResponse_<ContainerAllocator> Type;

  SetJointLimitPolicyResponse_()
    {
    }
  SetJointLimitPolicyResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointLimitPolicyResponse_

typedef ::sandia_hand_msgs::SetJointLimitPolicyResponse_<std::allocator<void> > SetJointLimitPolicyResponse;

typedef boost::shared_ptr< ::sandia_hand_msgs::SetJointLimitPolicyResponse > SetJointLimitPolicyResponsePtr;
typedef boost::shared_ptr< ::sandia_hand_msgs::SetJointLimitPolicyResponse const> SetJointLimitPolicyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sandia_hand_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sandia_hand_msgs': ['/home/chalmers/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/sandia-hand/ros/sandia_hand_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sandia_hand_msgs/SetJointLimitPolicyResponse";
  }

  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointLimitPolicyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sandia_hand_msgs::SetJointLimitPolicyResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SANDIA_HAND_MSGS_MESSAGE_SETJOINTLIMITPOLICYRESPONSE_H
