// Generated by gencpp from file sandia_hand_msgs/SimpleGraspWithSlewRequest.msg
// DO NOT EDIT!


#ifndef SANDIA_HAND_MSGS_MESSAGE_SIMPLEGRASPWITHSLEWREQUEST_H
#define SANDIA_HAND_MSGS_MESSAGE_SIMPLEGRASPWITHSLEWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sandia_hand_msgs/SimpleGrasp.h>

namespace sandia_hand_msgs
{
template <class ContainerAllocator>
struct SimpleGraspWithSlewRequest_
{
  typedef SimpleGraspWithSlewRequest_<ContainerAllocator> Type;

  SimpleGraspWithSlewRequest_()
    : grasp()
    , slew_duration(0.0)  {
    }
  SimpleGraspWithSlewRequest_(const ContainerAllocator& _alloc)
    : grasp(_alloc)
    , slew_duration(0.0)  {
  (void)_alloc;
    }



   typedef  ::sandia_hand_msgs::SimpleGrasp_<ContainerAllocator>  _grasp_type;
  _grasp_type grasp;

   typedef float _slew_duration_type;
  _slew_duration_type slew_duration;




  typedef boost::shared_ptr< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleGraspWithSlewRequest_

typedef ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<std::allocator<void> > SimpleGraspWithSlewRequest;

typedef boost::shared_ptr< ::sandia_hand_msgs::SimpleGraspWithSlewRequest > SimpleGraspWithSlewRequestPtr;
typedef boost::shared_ptr< ::sandia_hand_msgs::SimpleGraspWithSlewRequest const> SimpleGraspWithSlewRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sandia_hand_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sandia_hand_msgs': ['/home/chalmers/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/sandia-hand/ros/sandia_hand_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cec9206454ae797a395734c0dc1122b";
  }

  static const char* value(const ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cec9206454ae797ULL;
  static const uint64_t static_value2 = 0xa395734c0dc1122bULL;
};

template<class ContainerAllocator>
struct DataType< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sandia_hand_msgs/SimpleGraspWithSlewRequest";
  }

  static const char* value(const ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SimpleGrasp grasp\n\
float32 slew_duration\n\
\n\
================================================================================\n\
MSG: sandia_hand_msgs/SimpleGrasp\n\
string  name\n\
float64 closed_amount  \n\
# closed_amount = 0 means fully open\n\
# closed_amount = 1 means fully closed\n\
";
  }

  static const char* value(const ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasp);
      stream.next(m.slew_duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleGraspWithSlewRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sandia_hand_msgs::SimpleGraspWithSlewRequest_<ContainerAllocator>& v)
  {
    s << indent << "grasp: ";
    s << std::endl;
    Printer< ::sandia_hand_msgs::SimpleGrasp_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp);
    s << indent << "slew_duration: ";
    Printer<float>::stream(s, indent + "  ", v.slew_duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SANDIA_HAND_MSGS_MESSAGE_SIMPLEGRASPWITHSLEWREQUEST_H
